{
 "title": "ResilienceMetrics",
 "time": { "from": "2024-03-03T21:35:50.000Z", "to": "2024-03-03T22:22:20.000Z" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_count,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests Info (System.Net)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_client_request_duration_seconds_count{job=\"$job\",http_request_method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Successes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_client_request_duration_seconds_count{job=\"$job\",http_request_method=\"GET\", http_response_status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_client_request_duration_seconds_count{job=\"$job\",http_request_method=\"GET\", http_response_status_code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"$job\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"$job\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"$job\", error_type=~\"[a-z].+\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Connection Error"
    }
   ]
  },
  { "title": "Resilience Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Resilience Events",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event_name)(resilience_polly_strategy_events_total{event_name=~\"^On.*\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retries Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience_polly_strategy_events_total{event_name=\"OnRetry\", job=\"$job\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events by time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "count(resilience_polly_strategy_events_total{job=\"$job\", pipeline_name=\"MealDbClient-standard\"}) by (event_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeout Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience_polly_strategy_events_total{event_name=\"OnTimeout\", job=\"$job\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chaos Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Chaos Chart",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event_name)(resilience_polly_strategy_events_total{event_name=~\"^Chaos.*\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  }
 ]
}